### ISSUE TITLE
HACK CAR DEALER - zdejmowanie nadajnika

### ISSUE THREAD

**Issue by apokladowski** [KoRrNiK/fivecity_hack#1]
https://korrnik.github.io/fivecity_hack/car_dealer_gps/

[https://imgur.com/a/t6UbGqE](url)

**Comment by apokladowski** [comment]
Takie kwadraty w nienaturalnej wielkości pojawiają się tylko jeżeli wybierzemy większą szybkość pojawiania kwadratów.

**Comment by KoRrNiK** [comment]
Hejka,
- Jakiej przeglądarki korzystasz?
- Jaką masz rozdzielczość monitora?
- Na ile procent masz skalowanie w przeglądarce? ( ctrl + / ctrl - )

**Comment by apokladowski** [comment]
Hack testowałem na przeglądarce Firefox
1920 na 1080
90%

**Comment by KoRrNiK** [comment]
Za każdym razem Ci się tak dzieje czy co jakiś czas oraz czy tylko na większej szybkości.

**Comment by apokladowski** [comment]
Tylko na większej szybkości
