### ISSUE TITLE
Hack jubiler otwieranie głównego sejfu

### ISSUE THREAD

**Issue by ZwiastunPL** [KoRrNiK/fivecity_hack#2]
Pomimo wyznaczenia suwakiem poprawnej odpowiedzi równania, nie zalicza mi poprawnie wykonanego hacka, nie wiem czy to problem czy ja coś źle robię bo nie działa żaden ,,enter" ani żaden inny przycisk potwierdzający. Jakby można było to sprawdzić ewentualnie dopisać jak zatwierdzić wybraną liczbę.

**Comment by KoRrNiK** [comment]
Cześć, tak z ciekawości jakiej przeglądarki używasz?

Aby zaznaczyć poprawną odpowiedź trzeba było po zaznaczeniu kliknąć w suwak aby był zaznaczony.

Poprawiłem, że dowolne kliknięcie w ENTER aktywuje sprawdzenie wyniku.

**Comment by ZwiastunPL** [comment]
używam opery gx, i już wszystko działa bez problemowo, dziękuję za zmianę
